Repository dbt-labs/dbt-spark, pull requests merged in 2020-11, with the labels that each got.

#116 Support for ODBC driver connection type
  .circleci/config.yml
  .gitignore
  README.md
  dbt/adapters/spark/connections.py
  dev_requirements.txt
  requirements.txt
  setup.py
  test/integration/spark-databricks-http.dbtspec
  test/integration/spark-databricks-odbc-cluster.dbtspec
  test/integration/spark-databricks-odbc-sql-endpoint.dbtspec
  test/integration/spark-thrift.dbtspec
  test/unit/test_adapter.py
  tox.ini
Labels: enhancement

#121 Fix issue when installing pyodbc
  setup.py
Labels: bug

#120 Add changelog, issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: cla:yes

#127 Move PyHive requirement to extra
  CHANGELOG.md
  dbt/adapters/spark/connections.py
  setup.py
Labels: cla:yes
