Repository dbt-labs/dbt-spark, pull requests merged in 2022-11, with the labels that each got.

#508 [CT-1469] init pr for short term python version issue fix
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#509 [Backport][CT-1469] pr for short term python version issue fix
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#513 [CT-1486]dbt run fails with spark-testing profile of examples
  .changes/unreleased/Fixes-20221113-211208.yaml
  README.md
Labels: cla:yes

#516 Spark Implementation of flake8 fix to swap gitlab for github
  .pre-commit-config.yaml
Labels: cla:yes, Skip Changelog

#521 [BACKPORT] #403 to 1.1.latest
  .github/workflows/main.yml
  tests/functional/adapter/test_basic.py
Labels: cla:yes, Skip Changelog

#523 [Backport] [CT-1469] manual pr for short term python version issue fix
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#520 Supports new error messages.
  .changes/unreleased/Fixes-20221116-234601.yaml
  dbt/adapters/spark/impl.py
Labels: cla:yes, ready_for_review
