Repository dbt-labs/dbt-spark, pull requests merged in 2022-09, with the labels that each got.

#448 Update repo templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/ISSUE_TEMPLATE/release.md
  .github/dependabot.yml
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#462 add mypy ignore to column, connections and init
  .changes/unreleased/Under the Hood-20220913-152004.yaml
  dbt/adapters/spark/__init__.py
  dbt/adapters/spark/column.py
  dbt/adapters/spark/connections.py
  dbt/adapters/spark/impl.py
Labels: cla:yes

#463 Update changelog bot
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#451 [CT-1114] remove Cache call from get_columns_in_relation
  .changes/unreleased/Fixes-20220914-010520.yaml
  .pre-commit-config.yaml
  dbt/adapters/spark/impl.py
Labels: cla:yes

#469 Convert df to pyspark DataFrame if it is pandas before writing
  .changes/unreleased/Under the Hood-20220916-125706.yaml
  dbt/include/spark/macros/materializations/table.sql
Labels: cla:yes, ready_for_review

#471 Jpmmcneill/spark type boolean
  .changes/unreleased/Features-20220920-000814.yaml
  tests/functional/adapter/utils/test_data_types.py
Labels: cla:yes, ready_for_review

#467 More flexible cluster configuration
  .changes/unreleased/Features-20220923-101248.yaml
  dbt/adapters/spark/connections.py
  dbt/adapters/spark/impl.py
  dbt/adapters/spark/python_submissions.py
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#390 merge exclude columns spark
  .changes/unreleased/Features-20220826-133818.yaml
  dbt/include/spark/macros/materializations/incremental/column_helpers.sql
  dbt/include/spark/macros/materializations/incremental/strategies.sql
  dev-requirements.txt
  tests/integration/incremental_strategies/models_delta/merge_exclude_columns.sql
  tests/integration/incremental_strategies/seeds/expected_exclude_upsert.csv
  tests/integration/incremental_strategies/test_incremental_strategies.py
Labels: cla:yes, ready_for_review

#477 Remove branch ref from dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#454 Array macros
  .changes/unreleased/Features-20220913-084852.yaml
  dbt/include/spark/macros/utils/array_append.sql
  dbt/include/spark/macros/utils/array_concat.sql
  dbt/include/spark/macros/utils/array_construct.sql
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, ready_for_review

#475 Tests for `current_timestamp`
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, Skip Changelog

#474 Convert df to pyspark DataFrame if it is koalas before writing
  .changes/unreleased/Under the Hood-20220924-143713.yaml
  dbt/include/spark/macros/materializations/table.sql
Labels: cla:yes, Skip Changelog

#489 try/except rather than find_spec for optional imports
  dbt/include/spark/macros/materializations/table.sql
Labels: cla:yes, Skip Changelog

#493 rc bug fix
  dbt/adapters/spark/python_submissions.py
  dbt/include/spark/macros/materializations/table.sql
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, Skip Changelog
