Repository dbt-labs/dbt-spark, pull requests merged in 2023-06, with the labels that each got.

#788 adding link to 1.5 release notes
  .changes/0.0.0.md
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#794 Standardize the adapter for core debug changes
  .changes/unreleased/Features-20230604-043421.yaml
  dbt/adapters/spark/connections.py
  dbt/adapters/spark/impl.py
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes

#798 TestSparkConstraintQuotedColumn
  dev-requirements.txt
  tests/functional/adapter/test_constraints.py
Labels: cla:yes, Skip Changelog

#805 revert change to dev-requirements.txt
  dev-requirements.txt
Labels: cla:yes, Skip Changelog

#806 backport 798 to 1.5.latest
  tests/functional/adapter/test_constraints.py
Labels: Skip Changelog

#809 add dependent_projects_dict to utils.py
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#767 Disallow untyped `def`'s
  .changes/unreleased/Fixes-20230510-163110.yaml
  .pre-commit-config.yaml
  dbt/adapters/spark/column.py
  dbt/adapters/spark/connections.py
  dbt/adapters/spark/impl.py
  dbt/adapters/spark/python_submissions.py
  dbt/adapters/spark/relation.py
  dbt/adapters/spark/session.py
Labels: cla:yes

#784 Allow hostname to be provided with or without a trailing slash
  .changes/unreleased/Fixes-20230623-112100.yaml
  dbt/adapters/spark/connections.py
Labels: cla:yes

#819 Remove dependent_projects argument from PartialProject call in unit tests
  .changes/unreleased/Fixes-20230628-162413.yaml
  tests/unit/utils.py
Labels: cla:yes
