Repository dbt-labs/dbt-spark, pull requests merged in 2023-02, with the labels that each got.

#620 fix bug with contributor list
  .changie.yaml
Labels: cla:yes, Skip Changelog

#612 Convert Spark persist docs test
  tests/functional/adapter/persist_docs/fixtures.py
  tests/functional/adapter/persist_docs/test_persist_docs.py
  tests/integration/persist_docs/models/incremental_delta_model.sql
  tests/integration/persist_docs/models/my_fun_docs.md
  tests/integration/persist_docs/models/no_docs_model.sql
  tests/integration/persist_docs/models/table_delta_model.sql
  tests/integration/persist_docs/models/view_model.sql
  tests/integration/persist_docs/seeds/seed.csv
  tests/integration/persist_docs/seeds/seeds.yml
  tests/integration/persist_docs/test_persist_docs.py
Labels: cla:yes, Skip Changelog

#623 [BACKPORT] Remove PR requirement from Changelog
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#625 [BACKPORT] Remove PR requirement from Changelog
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#626 [BACKPORT] Remove PR requirement from Changelog
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#630 update regex for version bump
  .bumpversion.cfg
Labels: cla:yes, Skip Changelog

#619 [CI/CD] Backport release workflow to `1.4.latest`
  .bumpversion.cfg
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#618 [CI/CD] Backport release workflow to `1.3.latest`
  .bumpversion.cfg
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#616 [CI/CD] Backport release workflow to `1.1.latest`
  .bumpversion.cfg
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#617 [CI/CD] Backport release workflow to `1.2.latest`
  .bumpversion.cfg
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#629 convert test_store_test_failures to functional
  dev-requirements.txt
  tests/functional/adapter/store_test_failures_tests/test_store_test_failures.py
  tests/integration/store_failures/models/schema.yml
  tests/integration/store_failures/models/view_model.sql
  tests/integration/store_failures/test_store_failures.py
Labels: cla:yes, Skip Changelog

#601 Convert merge exclude columns tests
  .changes/unreleased/Fixes-20230123-134955.yaml
  tests/functional/adapter/incremental/test_incremental_merge_exclude_columns.py
  tests/integration/incremental_strategies/models_delta/merge_exclude_columns.sql
  tests/integration/incremental_strategies/seeds/expected_exclude_upsert.csv
  tests/integration/incremental_strategies/test_incremental_strategies.py
Labels: cla:yes, ready_for_review, pr_tracked

#614 remove invocation of integration tests in tox
  .changes/unreleased/Under the Hood-20230130-170310.yaml
  CONTRIBUTING.md
  tox.ini
Labels: cla:yes

#632 parse vars in unit test utils
  dbt/adapters/spark/impl.py
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#621 Sync Changelog team to GitHub team
  .bumpversion.cfg
  .changie.yaml
Labels: cla:yes, Skip Changelog

#643 CT-1967 - test conversion - get columns in relation
  Makefile
  tests/functional/adapter/test_get_columns_in_relation.py
  tests/integration/get_columns_in_relation/models/child.sql
  tests/integration/get_columns_in_relation/models/get_columns_from_child.sql
  tests/integration/get_columns_in_relation/test_get_columns_in_relation.py
Labels: cla:yes, Skip Changelog

#574 dbt Constraints / model contracts
  .changes/unreleased/Features-20230130-125855.yaml
  dbt/include/spark/macros/adapters.sql
  dbt/include/spark/macros/materializations/table.sql
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#556 Fix .gitignore for 1.1.latest
  .gitignore
Labels: cla:yes, Skip Changelog

#641 add new workflow for cutting .latest branches
  .github/workflows/cut-release-branch.yml
Labels: cla:yes, Skip Changelog

#648 add release prep secret
  .github/workflows/release.yml
Labels: Skip Changelog

#649 Rename constraints_enabled to contract
  .changes/unreleased/Under the Hood-20230223-105838.yaml
  dbt/include/spark/macros/adapters.sql
Labels: cla:yes

#650 add codeowners file
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#642 mirror issues to ADAP jira project
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes, Skip Changelog

#652 Revert "mirror issues to ADAP jira project"
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes

#637 remove seed_column_tests integration test
  tests/functional/adapter/seed_column_types/fixtures.py
  tests/functional/adapter/seed_column_types/test_seed_column_types.py
  tests/integration/seed_column_types/seeds/payments.csv
  tests/integration/seed_column_types/test_seed_column_types.py
Labels: cla:yes, Skip Changelog
