Repository dbt-labs/dbt-spark, pull requests merged in 2023-05, with the labels that each got.

#754 Remove unused `# type: ignore`
  .changes/unreleased/Under the Hood-20230508-222118.yaml
  .pre-commit-config.yaml
  dbt/adapters/spark/__init__.py
  dbt/adapters/spark/impl.py
Labels: cla:yes

#695 override schema_string_type fixture and test constraints for int type
  tests/functional/adapter/test_constraints.py
Labels: cla:yes, Skip Changelog

#759 Remove dead code 💀
  .changes/unreleased/Fixes-20230510-154735.yaml
  dbt/adapters/spark/impl.py
Labels: cla:yes, ready_for_review

#745 update used gh actions ahead of set-output, node12 deprecation
  .github/workflows/bot-changelog.yml
  .github/workflows/main.yml
  .github/workflows/triage-labels.yml
Labels: cla:yes, Skip Changelog

#773 [Backport] 1.1.latest gh deprecations
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#779 [BACKPORT] ADAP-473: Table materialization not properly dropping existing relati…
  .changes/unreleased/Fixes-20230420-214433.yaml
  dbt/include/spark/macros/materializations/table.sql
Labels: cla:yes

#780 [BACKPORT] ADAP-473: Table materialization not properly dropping existing relati…
  .changes/unreleased/Fixes-20230420-214433.yaml
  dbt/include/spark/macros/materializations/table.sql
Labels: cla:yes

#776 [Backport] 1.5.latest gh deprecations
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#775 [Backport] 1.4.latest gh deprecations
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#774 [Backport] 1.3.latest gh deprecations
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#783 update used gh actions ahead of node12 deprecation
  .github/workflows/backport.yml
  .github/workflows/bot-changelog.yml
  .github/workflows/main.yml
Labels: cla:yes, Skip Changelog

#747 Finish Constraint Support for Spark
  .changes/unreleased/Features-20230427-123135.yaml
  dbt/adapters/spark/impl.py
  dbt/include/spark/macros/adapters.sql
  tests/functional/adapter/test_constraints.py
Labels: cla:yes

#793 drop support for python 3.7
  .changes/unreleased/Under the Hood-20230530-162533.yaml
  .github/workflows/main.yml
  CONTRIBUTING.md
  dev-requirements.txt
  setup.py
  tox.ini
Labels: cla:yes
