Repository dbt-labs/dbt-spark, pull requests merged in 2023-01, with the labels that each got.

#578 add databricks integ tests back
  .circleci/config.yml
  tests/functional/adapter/test_python_model.py
  tox.ini
Labels: cla:yes, Skip Changelog

#582 Use CircleCI Context for AWS access key environment variables
  .circleci/config.yml
  tox.ini
Labels: cla:yes, Skip Changelog

#573 add escape_single_quotes macro
  .changes/unreleased/Fixes-20221221-092410.yaml
  dbt/include/spark/macros/utils/escape_single_quotes.sql
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes, ready_for_review

#585 rename exceptions
  .changes/unreleased/Under the Hood-20230110-101919.yaml
  dbt/adapters/spark/connections.py
  dbt/adapters/spark/impl.py
  dbt/adapters/spark/python_submissions.py
  dbt/adapters/spark/relation.py
  tests/integration/incremental_on_schema_change/test_incremental_on_schema_change.py
  tests/integration/incremental_strategies/test_incremental_strategies.py
  tests/integration/persist_docs/test_persist_docs.py
  tests/integration/seed_column_types/test_seed_column_types.py
  tests/unit/test_adapter.py
Labels: cla:yes

#576 wrap if expression in brackets
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#399 make dev installs requirements.txt too
  Makefile
Labels: cla:yes, Stale

#593 Convert incremental on_schema_change tests
  tests/functional/adapter/incremental/test_incremental_on_schema_change.py
  tests/functional/adapter/incremental/test_incremental_predicates.py
  tests/functional/adapter/incremental/test_incremental_unique_id.py
  tests/integration/incremental_on_schema_change/models/incremental_append_new_columns.sql
  tests/integration/incremental_on_schema_change/models/incremental_append_new_columns_target.sql
  tests/integration/incremental_on_schema_change/models/incremental_fail.sql
  tests/integration/incremental_on_schema_change/models/incremental_ignore.sql
  tests/integration/incremental_on_schema_change/models/incremental_ignore_target.sql
  tests/integration/incremental_on_schema_change/models/incremental_sync_all_columns.sql
  tests/integration/incremental_on_schema_change/models/incremental_sync_all_columns_target.sql
  tests/integration/incremental_on_schema_change/models/model_a.sql
  tests/integration/incremental_on_schema_change/test_incremental_on_schema_change.py
Labels: cla:yes, Skip Changelog

#598 add context var for aws creds
  .circleci/config.yml
Labels: cla:yes, Skip Changelog

#604 Use AttrDict instead of agate
  dbt/adapters/spark/impl.py
Labels: cla:yes, Skip Changelog

#605 Upgrade Thrift to 0.16.0
  .changes/unreleased/Dependencies-20230126-152319.yaml
  setup.py
Labels: cla:yes

#592 [CI/CD] Update release workflow
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#603 Remove PR requirement from Changelog
  .changie.yaml
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#613 [CI/CD] Update release workflow definition
  .github/workflows/release.yml
Labels: cla:yes, Skip Changelog

#611 change type to string
  .changie.yaml
Labels: cla:yes, Skip Changelog
