Repository dbt-labs/dbt-spark, pull requests merged in 2024-05, with the labels that each got.

#1034 Skip tests on `main` to unblock CI, create issues to fix them
  tests/functional/adapter/test_constraints.py
  tests/functional/adapter/test_python_model.py
Labels: cla:yes, Skip Changelog

#1039 Add missing changelog backlinks.
  CHANGELOG.md
Labels: cla:yes, Skip Changelog

#1040 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#1026 Move to `pre-commit` only
  .flake8
  .github/workflows/integration.yml
  .github/workflows/main.yml
  .pre-commit-config.yaml
  Makefile
  dbt/adapters/spark/__init__.py
  dbt/adapters/spark/column.py
  dbt/adapters/spark/connections.py
  dbt/adapters/spark/impl.py
  dev-requirements.txt
  tests/unit/utils.py
Labels: cla:yes, Skip Changelog

#1041 [Bug] Fix constraints enforcement rollover test
  requirements.txt
  test.env.example
  tests/functional/adapter/test_constraints.py
Labels: cla:yes, Skip Changelog

#1030 Cross-database `date` macro
  .changes/unreleased/Features-20240501-151904.yaml
  dbt/include/spark/macros/utils/date.sql
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes

#1042 [Bug] Fix incremental python tables - dbt can't find temporary table transaction logs
  .changes/unreleased/Fixes-20240513-160121.yaml
  dbt/include/spark/macros/materializations/incremental/incremental.sql
  requirements.txt
  tests/functional/adapter/test_python_model.py
Labels: cla:yes

#1029 Import relevant pytest(s) for cross-database `cast` macro
  .changes/unreleased/Features-20240430-185723.yaml
  tests/functional/adapter/utils/test_utils.py
Labels: cla:yes

#1045 Bump deps on common, adapters, core
  setup.py
Labels: cla:yes, Skip Changelog, backport 1.8.latest

#1004 Add docker release to the full release process for final releases
  .github/dependabot.yml
  .github/workflows/release.yml
  Makefile
  docker-compose.yml
  docker/Dockerfile
  docker/README.md
  docker/spark.Dockerfile
Labels: cla:yes, Skip Changelog
