Repository dbt-labs/dbt-spark, pull requests merged in 2024-02, with the labels that each got.

#986 fix spark cluster start mechanism and add extra dev requirements
  dagger/run_dbt_spark_tests.py
  dev-requirements.txt
  tests/functional/conftest.py
Labels: Skip Changelog

#976 Add functional tests for unit testing
  .changes/unreleased/Features-20240220-195925.yaml
  dbt/include/spark/macros/adapters.sql
  dbt/include/spark/macros/utils/safe_cast.sql
  tests/functional/adapter/unit_testing/test_unit_testing.py
Labels: cla:yes

#977 Remove actions that sync github and jira
  .github/workflows/jira-creation.yml
  .github/workflows/jira-label.yml
  .github/workflows/jira-transition.yml
Labels: cla:yes, Skip Changelog, support

#992 update dbt-common dependency to <2.0
  setup.py
Labels: cla:yes, Skip Changelog

#993 Include a pre-release in the dbt-adapters pin to allow pre-releases to be installed on main
  setup.py
Labels: cla:yes, Skip Changelog, support
